config/routes.rb
Rails.application.routes.draw do
  resources :breweries
  root 'beers#index'
  resources :users

  resources :beers do
    post 'like'
    post 'dislike'
    resources :comments
    collection do
      get 'random'
    end
  end

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  acts_as_votable
  belongs_to :brewery
  has_many :comments, as: :commentable
  def self.random_beer
    Beer.order("RANDOM()").limit(1).first
  end
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  has_many :beers, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  acts_as_voter
  def name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]
  before_action :set_vote_beer, only: [:like, :dislike]

  def like
    @beer.liked_by current_user
    redirect_to random_beers_path, notice: 'You liked it!'
  end

  def dislike
    @beer.dislike_by current_user
    redirect_to random_beers_path, notice: "Next time!"
  end

  def random
    @beer = Beer.random_beer
    redirect_to beers_url, notice: "Here's another one!"
  end

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all
    @random = Beer.random_beer
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    def set_vote_beer
      @beer = Beer.find(params[:beer_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :brewery_id, :category, :price, :available, :volume, :alcohol_percentage)
    end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)
    if @brewery.save
      redirect_to breweries_path, notice: 'Brewery was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
      if @brewery.update(brewery_params)
      redirect_to breweries_path, notice: 'Brewery was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
      Redirect_to breweries_url, notice: 'Brewery was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :country)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.new(comment_params)

    if @comment.save
      redirect_to :back, notice: 'Your comment was successfully posted!'
    else
      redirect_to :back, notice: "Your comment wasn't posted!"
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end

    def find_commentable
      # @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
      # @commentable = Beer.find_by_id(params[:beer_id]) if params[:beer_id]
      @commentable = Beer.find(params[:beer_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to beers_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :password)
    end
end

app/views/application/_current_user.html.haml
- if signed_in?
  %p
    = current_user.email
    \/
    = link_to 'Sign out', sign_out_path, method: :delete
- else
  = link_to 'Sign in', sign_in_path
#flash
  - flash.each do |key, value|
    %div{:class => "flash #{key}"}= value

app/views/application/_footer.html.haml
%footer
  Built with &hearts; in Stockholm by Aron Strandberg &amp; Shayan Effati

app/views/application/_header.html.haml
%h1= link_to 'drankt', root_path
- if signed_in?
  %p
    = link_to "#{current_user.email}", user_path(current_user.id)
    \/
    = link_to 'Sign out', sign_out_path, method: :delete
- else
  = link_to 'Sign in', sign_in_path
#flash
  - flash.each do |key, value|
    %div{:class => "flash #{key}"}= value

app/views/beers/_beer.html.haml
%li.beer
  = link_to beer do
    .text
      %h1= beer.name
      %h4= beer.brewery.name if beer.brewery
      %table
        %tr
          %th category
          %th price
          %th volume
          %th alcohol
          %th 🍻
          %th 💩
        %tr
          %td= beer.category
          %td= beer.price
          %td= "#{beer.volume / 10} cl"
          %td= "#{beer.alcohol_percentage}%"
          %td= beer.get_likes.size
          %td= beer.get_dislikes.size

app/views/beers/_comment.html.haml
%li.comment
  –
  = comment.body

app/views/beers/_form.html.haml
= form_for @beer do |f|
  - if @beer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@beer.errors.count, "error")} prohibited this beer from being saved:"
      %ul
        - @beer.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :category
    = f.text_field :category
  .field
    = f.label :volume
    = f.number_field :volume
  .field
    = f.label :alcohol_percentage
    = f.text_field :alcohol_percentage
  .field
    = f.label :price
    = f.number_field :price
  .field
    = f.label :available
    = f.check_box :available
  .field
    = f.label :brewery
    /= select_tag 'id', options_from_collection_for_select(@breweries, 'id', 'name')
    = f.collection_select :brewery_id, Brewery.all, :id, :name
  .actions
    = f.submit 'Save'

app/views/beers/edit.html.haml
%h1 Editing beer

= render 'form'

= button_to 'Show', @beer, method: :get
= button_to 'Back', beers_path, method: :get

app/views/beers/index.html.haml
- if signed_in?
  %h3 Here's a random beer to try:
  %ul.beers.random
    = render partial: "beer", locals: {beer: @random}
    = button_to "Yes, I liked it", beer_like_path(beer_id: @random.id), {class: 'accept'}
    = button_to "Hm, gimme something else", random_beers_path, method: :get
    = button_to "No, hated it", beer_dislike_path(beer_id: @random.id), {class: 'decline'}

  %h3 Here's our other beers

  %ul.beers
    = render @beers - [@random]
    = button_to 'New beer', new_beer_path, method: :get
- if !signed_in?
  %h1 Please sign in to use drankt

app/views/beers/new.html.haml
%h1 New beer

= render 'form'

= button_to 'Back', beers_path, {method: :get, locals: {beers: @beers}}

app/views/beers/show.html.haml
%p#notice= notice

.beer.details
  %p
    %b Name:
    = @beer.name
  %p
    %b Brewery:
    = @beer.brewery.name unless @beer.brewery.nil?
  %p
    %b Category:
    = @beer.category
  %p
    %b Price:
    = "#{@beer.price}:-"
  %p
    %b Available:
    = @beer.available
  %p
    %b Country:
    = @beer.brewery.country unless @beer.brewery.nil?
  %p
    %b Volume:
    = @beer.volume
  %p
    %b Alcohol percentage:
    = @beer.alcohol_percentage


= form_for [@beer, Comment.new] do |f|
  = f.text_field :body, placeholder: "Add a comment"

%h3 Comments
.comments
  %ul= render partial: 'comment', collection: @beer.comments

= button_to 'Edit', edit_beer_path(@beer), method: :get
= button_to 'Back', beers_path, method: :get

app/views/breweries/_form.html.haml
= form_for @brewery do |f|
  - if @brewery.errors.any?
    #error_explanation
      %h2= "#{pluralize(@brewery.errors.count, "error")} prohibited this brewery from being saved:"
      %ul
        - @brewery.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :country
    = f.text_field :country
  .actions
    = f.submit 'Save'

app/views/breweries/edit.html.haml
%h1 Editing brewery

= render 'form'

= button_to 'Back', breweries_path, method: :get

app/views/breweries/index.html.haml
%h1 Listing breweries

%table
  %thead
    %tr
      %th Name
      %th Country
      %th
      %th

  %tbody
    - @breweries.each do |brewery|
      %tr
        %td= brewery.name
        %td= brewery.country
        %td= button_to 'Edit', edit_brewery_path(brewery), method: :get
        %td= button_to 'Destroy', brewery, method: :delete, data: { :confirm => 'Are you sure?' }

%br

= button_to 'New Brewery', new_brewery_path, method: :get

app/views/breweries/new.html.haml
%h1 New brewery

= render 'form'

= link_to 'Back', breweries_path

app/views/breweries/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @brewery.name
%p
  %b Country:
  = @brewery.country

= link_to 'Edit', edit_brewery_path(@brewery)
\|
= link_to 'Back', breweries_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Drankt
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://use.typekit.net/wjb5wpp.js'
    :javascript
        try{Typekit.load({ async: true });}catch(e){}
    = csrf_meta_tags
  %body
    = render partial: 'header'
    = yield
    = render partial: 'footer'

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email, type: 'email'
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .submit-field
    = form.submit

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Email
      %th First name
      %th Last name

  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td= user.first_name
        %td= user.last_name

app/views/users/new.html.haml
#clearance.sign-up
  %h2= t(".title")
  = form_for @user do |form|
    = render partial: '/users/form', object: form

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @user.email
%p
  %b First name:
  = @user.first_name
%p
  %b Last name:
  = @user.last_name

%p
  %b Beers you liked:
%ul
  - @user.find_liked_items.each do |beer|
    %li= beer.name

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path